package diet.eat.ventanas;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Angel
 */
public class Inicio2 extends javax.swing.JFrame {

    private Object receta1;

    /**
     * Creates new form Inicio2
     */
    public Inicio2() {
        initComponents();
        Feliz.setVisible(false);
        feliz2.setVisible(false);
        Desnutricion.setVisible(false);
        SobrePeso.setVisible(false);
        Obesidad.setVisible(false);
        IMAGEN1.setVisible(true);
        IMAGEN2.setVisible(false);
        IMAGEN3.setVisible(false);
        LBFlechaDer1.setVisible(true);
        LBFlechaDer2.setVisible(false);
        LBFlechaDer3.setVisible(false);
        LBFlechaIzq.setVisible(true);
        LBFlechaIzq1.setVisible(false);
        LBFlechaIzq2.setVisible(false);
        JLSaltar.setVisible(false);
        JLSano.setVisible(false);
        JLCaminar.setVisible(false);
        JLComer.setVisible(false);
        JLDatos.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        PnlPerfil = new javax.swing.JTabbedPane();
        Inicio = new javax.swing.JPanel();
        salir = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LBFlechaDer3 = new javax.swing.JLabel();
        LBFlechaDer2 = new javax.swing.JLabel();
        IMAGEN3 = new javax.swing.JLabel();
        IMAGEN2 = new javax.swing.JLabel();
        LBFlechaDer1 = new javax.swing.JLabel();
        LBFlechaIzq = new javax.swing.JLabel();
        LBFlechaIzq2 = new javax.swing.JLabel();
        LBFlechaIzq1 = new javax.swing.JLabel();
        IMAGEN1 = new javax.swing.JLabel();
        FONDO = new javax.swing.JLabel();
        Calcular = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TXTEJ2 = new javax.swing.JLabel();
        TXTEJ1 = new javax.swing.JLabel();
        PesoKg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AlturaCm = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        Feliz = new javax.swing.JLabel();
        feliz2 = new javax.swing.JLabel();
        Desnutricion = new javax.swing.JLabel();
        SobrePeso = new javax.swing.JLabel();
        Obesidad = new javax.swing.JLabel();
        Calendario = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        JLTuPeso = new javax.swing.JLabel();
        JBBorrar = new javax.swing.JButton();
        JLDatos = new javax.swing.JLabel();
        JLSaltar = new javax.swing.JLabel();
        JLCaminar = new javax.swing.JLabel();
        JLComer = new javax.swing.JLabel();
        JLSano = new javax.swing.JLabel();
        Recetas = new javax.swing.JPanel();
        JLReceta1 = new javax.swing.JLabel();
        JLTiktok = new javax.swing.JLabel();
        INGRE1 = new javax.swing.JLabel();
        INGRE2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PnlPerfilMouseClicked(evt);
            }
        });

        Inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diet/eat/ventanas/imaIconos/salir.png"))); // NOI18N
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        Inicio.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 40, 40));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DESCUBRE NUESTRAS RECETAS");
        Inicio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        LBFlechaDer3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diet/eat/ventanas/imaIconos/flecha der.png"))); // NOI18N
        LBFlechaDer3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBFlechaDer3MouseClicked(evt);
            }
        });
        Inicio.add(LBFlechaDer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 80, -1));

        LBFlechaDer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diet/eat/ventanas/imaIconos/flecha der.png"))); // NOI18N
        LBFlechaDer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBFlechaDer2MouseClicked(evt);
            }
        });
        Inicio.add(LBFlechaDer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 80, -1));

        IMAGEN3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diet/eat/ventanas/imaRecetas/3.jpg"))); // NOI18N
        IMAGEN3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IMAGEN3MouseClicked(evt);
            }
        });
        Inicio.add(IMAGEN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 540, 360));

        IMAGEN2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diet/eat/ventanas/imaRecetas/2.jpg"))); // NOI18N
        Inicio.add(IMAGEN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, 360));

        LBFlechaDer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diet/eat/ventanas/imaIconos/flecha der.png"))); // NOI18N
        LBFlechaDer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBFlechaDer1MouseClicked(evt);
            }
        });
        Inicio.add(LBFlechaDer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 80, -1));

        LBFlechaIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diet/eat/ventanas/imaIconos/flecha izq.png"))); // NOI18N
        LBFlechaIzq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBFlechaIzqMouseClicked(evt);
            }
        });
        Inicio.add(LBFlechaIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        LBFlechaIzq2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diet/eat/ventanas/imaIconos/flecha izq.png"))); // NOI18N
        LBFlechaIzq2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBFlechaIzq2MouseClicked(evt);
            }
        });
        Inicio.add(LBFlechaIzq2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        LBFlechaIzq1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diet/eat/ventanas/imaIconos/flecha izq.png"))); // NOI18N
        LBFlechaIzq1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBFlechaIzq1MouseClicked(evt);
            }
        });
        Inicio.add(LBFlechaIzq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        IMAGEN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diet/eat/ventanas/imaRecetas/1.jpg"))); // NOI18N
        Inicio.add(IMAGEN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 520, 360));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diet/eat/ventanas/imaInicio/paisaje.gif"))); // NOI18N
        Inicio.add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 773, 461));

        PnlPerfil.addTab("Inicio", Inicio);

        Calcular.setBackground(new java.awt.Color(255, 255, 255));
        Calcular.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diet/eat/ventanas/imaLogin/logo png (1).png"))); // NOI18N
        Calcular.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Peso en Kg:");
        Calcular.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        TXTEJ2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        TXTEJ2.setForeground(new java.awt.Color(153, 153, 153));
        TXTEJ2.setText("1.70 Mts");
        TXTEJ2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TXTEJ2MouseClicked(evt);
            }
        });
        Calcular.add(TXTEJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 80, 30));

        TXTEJ1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        TXTEJ1.setForeground(new java.awt.Color(153, 153, 153));
        TXTEJ1.setText("50 KG");
        TXTEJ1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TXTEJ1MouseClicked(evt);
            }
        });
        Calcular.add(TXTEJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 60, 30));

        PesoKg.setBackground(new java.awt.Color(204, 204, 204));
        PesoKg.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PesoKg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PesoKgMouseClicked(evt);
            }
        });
        PesoKg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesoKgActionPerformed(evt);
            }
        });
        Calcular.add(PesoKg, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 160, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Altura en Mts :");
        Calcular.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        AlturaCm.setBackground(new java.awt.Color(204, 204, 204));
        AlturaCm.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        AlturaCm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlturaCmMouseClicked(evt);
            }
        });
        AlturaCm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlturaCmActionPerformed(evt);
            }
        });
        Calcular.add(AlturaCm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 160, 30));

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diet/eat/ventanas/imaIconos/calculadora.png"))); // NOI18N
        jToggleButton1.setText("Calcular");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        Calcular.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 120, 50));

        Feliz.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Feliz.setForeground(new java.awt.Color(0, 0, 0));
        Feliz.setText("Felicitaciones tu peso es el optimo y");
        Calcular.add(Feliz, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 340, 70));

        feliz2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        feliz2.setForeground(new java.awt.Color(0, 0, 0));
        feliz2.setText("cuentas con una buena salud");
        Calcular.add(feliz2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        Desnutricion.setBackground(new java.awt.Color(255, 255, 255));
        Desnutricion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Desnutricion.setForeground(new java.awt.Color(0, 0, 0));
        Desnutricion.setText("Losentimos, Pero te encuentras en Desnutricion");
        Calcular.add(Desnutricion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        SobrePeso.setBackground(new java.awt.Color(255, 255, 255));
        SobrePeso.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        SobrePeso.setForeground(new java.awt.Color(0, 0, 0));
        SobrePeso.setText("Losentimos, Pero te encuentras en SobrePeso");
        Calcular.add(SobrePeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        Obesidad.setBackground(new java.awt.Color(255, 255, 255));
        Obesidad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Obesidad.setForeground(new java.awt.Color(0, 0, 0));
        Obesidad.setText("Losentimos, Pero te encuentras en Obesidad");
        Calcular.add(Obesidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        Calendario.setBackground(new java.awt.Color(255, 255, 255));
        Calendario.setForeground(new java.awt.Color(255, 255, 255));
        Calcular.add(Calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 180, 40));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Fecha de Nacimiento :");
        Calcular.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 280, -1));

        JLTuPeso.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JLTuPeso.setForeground(new java.awt.Color(0, 0, 0));
        JLTuPeso.setText("Tu peso Ideal es :");
        Calcular.add(JLTuPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        JBBorrar.setBackground(new java.awt.Color(255, 255, 255));
        JBBorrar.setForeground(new java.awt.Color(0, 0, 0));
        JBBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diet/eat/ventanas/imaIconos/BORRAR.png"))); // NOI18N
        JBBorrar.setText("Borrar");
        JBBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBorrarActionPerformed(evt);
            }
        });
        Calcular.add(JBBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 110, 50));

        JLDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diet/eat/ventanas/imaVideos/datos.gif"))); // NOI18N
        Calcular.add(JLDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        JLSaltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diet/eat/ventanas/imaVideos/saltar.gif"))); // NOI18N
        Calcular.add(JLSaltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, -1, -1));

        JLCaminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diet/eat/ventanas/imaVideos/caminar.gif"))); // NOI18N
        Calcular.add(JLCaminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        JLComer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diet/eat/ventanas/imaVideos/comer.gif"))); // NOI18N
        Calcular.add(JLComer, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 230, 170));

        JLSano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diet/eat/ventanas/imaVideos/sano.gif"))); // NOI18N
        Calcular.add(JLSano, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        PnlPerfil.addTab("Calcular", Calcular);

        JLReceta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diet/eat/ventanas/imaVideos/receta1.gif"))); // NOI18N

        JLTiktok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diet/eat/ventanas/imaVideos/receta2.gif"))); // NOI18N

        INGRE1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        INGRE1.setForeground(new java.awt.Color(0, 0, 51));
        INGRE1.setText("INGREDIENTES");
        INGRE1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INGRE1MouseClicked(evt);
            }
        });

        INGRE2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        INGRE2.setForeground(new java.awt.Color(0, 0, 51));
        INGRE2.setText("INGREDIENTES");
        INGRE2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INGRE2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout RecetasLayout = new javax.swing.GroupLayout(Recetas);
        Recetas.setLayout(RecetasLayout);
        RecetasLayout.setHorizontalGroup(
            RecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecetasLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(JLReceta1)
                .addGap(53, 53, 53)
                .addComponent(JLTiktok)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(RecetasLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(INGRE1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(INGRE2)
                .addGap(156, 156, 156))
        );
        RecetasLayout.setVerticalGroup(
            RecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecetasLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(RecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLReceta1)
                    .addComponent(JLTiktok, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INGRE1)
                    .addComponent(INGRE2))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        PnlPerfil.addTab("Recetas", Recetas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        if (!PesoKg.getText().isEmpty() && !AlturaCm.getText().isEmpty()) {

            try {
                double peso = Double.parseDouble(PesoKg.getText());
                double altura = Double.parseDouble(AlturaCm.getText());

                double IMC = calcularIMC(peso, altura);
                double PI = pesoIdeal(peso, altura);

                String cadena = String.valueOf(PI);
                JLTuPeso.setText("Tu peso ideal es: " + cadena);
                JLDatos.setVisible(false);

                if (IMC >= 18.5 && IMC <= 24.9) {
                    Feliz.setVisible(true);
                    feliz2.setVisible(true);
                    JLSano.setVisible(true);

                } else {
                    if (IMC < 18.5) {
                        //Desnutricion
                        Desnutricion.setVisible(true);
                        JLComer.setVisible(true);
                    } else {
                        if (IMC > 24.9 && IMC < 28) {
                            //SobrePeso
                            SobrePeso.setVisible(true);
                            JLCaminar.setVisible(true);
                        } else {
                            //Obesidad
                            Obesidad.setVisible(true);
                            JLSaltar.setVisible(true);
                        }
                    }
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Error: Ingresa un número decimal válido.");
            }

        } else {
            JOptionPane.showMessageDialog(null, "el campo no puede estar vacio");
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void AlturaCmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlturaCmActionPerformed

    }//GEN-LAST:event_AlturaCmActionPerformed

    private void PesoKgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesoKgActionPerformed


    }//GEN-LAST:event_PesoKgActionPerformed

    private void LBFlechaIzq1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBFlechaIzq1MouseClicked
        IMAGEN1.setVisible(true);
        IMAGEN2.setVisible(false);
        IMAGEN3.setVisible(false);
        LBFlechaIzq.setVisible(true);
        LBFlechaIzq1.setVisible(false);
        LBFlechaIzq2.setVisible(false);
        LBFlechaDer1.setVisible(true);
        LBFlechaDer2.setVisible(false);
        LBFlechaDer3.setVisible(false);
    }//GEN-LAST:event_LBFlechaIzq1MouseClicked

    private void LBFlechaIzq2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBFlechaIzq2MouseClicked
        IMAGEN1.setVisible(false);
        IMAGEN2.setVisible(true);
        IMAGEN3.setVisible(false);
        LBFlechaIzq.setVisible(false);
        LBFlechaIzq1.setVisible(true);
        LBFlechaIzq2.setVisible(false);
        LBFlechaDer1.setVisible(false);
        LBFlechaDer2.setVisible(true);
        LBFlechaDer3.setVisible(false);
    }//GEN-LAST:event_LBFlechaIzq2MouseClicked

    private void LBFlechaIzqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBFlechaIzqMouseClicked
        IMAGEN1.setVisible(false);
        IMAGEN2.setVisible(false);
        IMAGEN3.setVisible(true);
        LBFlechaIzq.setVisible(false);
        LBFlechaIzq1.setVisible(false);
        LBFlechaIzq2.setVisible(true);
        LBFlechaDer1.setVisible(false);
        LBFlechaDer2.setVisible(false);
        LBFlechaDer3.setVisible(true);
    }//GEN-LAST:event_LBFlechaIzqMouseClicked

    @SuppressWarnings("empty-statement")
    private void LBFlechaDer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBFlechaDer1MouseClicked
        IMAGEN1.setVisible(false);
        IMAGEN2.setVisible(true);
        IMAGEN3.setVisible(false);
        LBFlechaDer1.setVisible(false);
        LBFlechaDer2.setVisible(true);
        LBFlechaDer3.setVisible(false);
        LBFlechaIzq.setVisible(false);
        LBFlechaIzq1.setVisible(true);
        LBFlechaIzq2.setVisible(false);
    }//GEN-LAST:event_LBFlechaDer1MouseClicked

    private void LBFlechaDer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBFlechaDer2MouseClicked
        IMAGEN1.setVisible(false);
        IMAGEN2.setVisible(false);

        LBFlechaDer1.setVisible(false);
        LBFlechaDer2.setVisible(false);

        LBFlechaIzq.setVisible(false);
        LBFlechaIzq1.setVisible(false);

        LBFlechaIzq2.setVisible(true);
        IMAGEN3.setVisible(true);
        LBFlechaDer3.setVisible(true);
    }//GEN-LAST:event_LBFlechaDer2MouseClicked

    private void LBFlechaDer3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBFlechaDer3MouseClicked
        IMAGEN1.setVisible(true);
        IMAGEN2.setVisible(false);
        IMAGEN3.setVisible(false);
        LBFlechaDer1.setVisible(true);
        LBFlechaDer2.setVisible(false);
        LBFlechaDer3.setVisible(false);
        LBFlechaIzq.setVisible(true);
        LBFlechaIzq1.setVisible(false);
        LBFlechaIzq2.setVisible(false);
    }//GEN-LAST:event_LBFlechaDer3MouseClicked

    private void IMAGEN3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IMAGEN3MouseClicked

    }//GEN-LAST:event_IMAGEN3MouseClicked

    private void PesoKgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PesoKgMouseClicked
        TXTEJ1.setVisible(false);


    }//GEN-LAST:event_PesoKgMouseClicked

    private void JBBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBorrarActionPerformed
        PesoKg.setText("");
        AlturaCm.setText("");
        Feliz.setVisible(false);
        Desnutricion.setVisible(false);
        Obesidad.setVisible(false);
        SobrePeso.setVisible(false);
        Calendario.setDate(null);
        TXTEJ1.setVisible(true);
        TXTEJ2.setVisible(true);
        JLDatos.setVisible(true);
        feliz2.setVisible(false);
        JLSano.setVisible(false);
         JLComer.setVisible(false);
           JLCaminar.setVisible(false);
           JLSaltar.setVisible(false);
            JLTuPeso.setText("Tu peso ideal es: ");
    }//GEN-LAST:event_JBBorrarActionPerformed

    private void INGRE1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INGRE1MouseClicked

        JOptionPane.showMessageDialog(this, "INGREDIENTES: \n 6 tazas de arina \n 1 poco de sal \n 3 cucharitas de levadura deshidratada \n 3 tazas de agua ", "RECETA #1", JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_INGRE1MouseClicked

    private void INGRE2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INGRE2MouseClicked
// 
        JOptionPane.showMessageDialog(this, "Ingredientes:\n 1 brócoli \n 2 huevos \n ajo en polvo\n 40gr de queso rallado \n 2 cucharadas de harina de avena\n 1½ cucharadas de panko o pan rallado\n sal y pimienta ", "RECETA #2", JOptionPane.INFORMATION_MESSAGE);

        // TODO add your handling code here:
    }//GEN-LAST:event_INGRE2MouseClicked

    private void TXTEJ1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTEJ1MouseClicked
        TXTEJ1.setVisible(false);
    }//GEN-LAST:event_TXTEJ1MouseClicked

    private void TXTEJ2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTEJ2MouseClicked
        TXTEJ2.setVisible(false); 

    }//GEN-LAST:event_TXTEJ2MouseClicked

    private void AlturaCmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlturaCmMouseClicked
        TXTEJ2.setVisible(false);

    }//GEN-LAST:event_AlturaCmMouseClicked

    private void PnlPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlPerfilMouseClicked
        TXTEJ1.setVisible(true);
        TXTEJ2.setVisible(true);
    }//GEN-LAST:event_PnlPerfilMouseClicked

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
         Login Fr = new Login();
            Fr.setSize(960,540);
            Fr.setVisible(true);
            Fr.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_salirMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlturaCm;
    private javax.swing.JPanel Calcular;
    private com.toedter.calendar.JDateChooser Calendario;
    private javax.swing.JLabel Desnutricion;
    private javax.swing.JLabel FONDO;
    private javax.swing.JLabel Feliz;
    private javax.swing.JLabel IMAGEN1;
    private javax.swing.JLabel IMAGEN2;
    private javax.swing.JLabel IMAGEN3;
    private javax.swing.JLabel INGRE1;
    private javax.swing.JLabel INGRE2;
    private javax.swing.JPanel Inicio;
    private javax.swing.JButton JBBorrar;
    private javax.swing.JLabel JLCaminar;
    private javax.swing.JLabel JLComer;
    private javax.swing.JLabel JLDatos;
    private javax.swing.JLabel JLReceta1;
    private javax.swing.JLabel JLSaltar;
    private javax.swing.JLabel JLSano;
    private javax.swing.JLabel JLTiktok;
    private javax.swing.JLabel JLTuPeso;
    private javax.swing.JLabel LBFlechaDer1;
    private javax.swing.JLabel LBFlechaDer2;
    private javax.swing.JLabel LBFlechaDer3;
    private javax.swing.JLabel LBFlechaIzq;
    private javax.swing.JLabel LBFlechaIzq1;
    private javax.swing.JLabel LBFlechaIzq2;
    private javax.swing.JLabel Obesidad;
    private javax.swing.JTextField PesoKg;
    private javax.swing.JTabbedPane PnlPerfil;
    private javax.swing.JPanel Recetas;
    private javax.swing.JLabel SobrePeso;
    private javax.swing.JLabel TXTEJ1;
    private javax.swing.JLabel TXTEJ2;
    private javax.swing.JLabel feliz2;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel salir;
    // End of variables declaration//GEN-END:variables

    public static double calcularIMC(double peso, double altura) {
        return peso / (altura * altura);
        //PesoIdeal
        // 22*AlturaCm^2=PesoIdeal
        //
    }

    public static double pesoIdeal(double peso, double altura) {

        return 22 * (altura * altura);

    }
}
